proxy:
  type: wpad
  wpadUrl: "http://wpad/wpad.dat"

kerberos:
  enableCache: true

ebpf:
  targetPorts: [80, 443]
  excluded:
    - "/usr/local/bin/kernelgatekeeper-service"
    - "/usr/local/bin/kernelgatekeeper-client"
    - "/opt/cisco/secureclient/bin/vpnagentd"

logLevel: "debug"
logPath: "/var/log/kernelgatekeeper.log"

shutdownTimeout: 30
socketPath: "/var/run/kernelgatekeeper.sock"