# config.yaml
proxy:
  type: http # http, https, wpad, none (Used by Client)
  url: "http://proxy.example.com:3128" # Used by Client if type=http/https
  wpad_url: "http://wpad.example.com/wpad.dat" # Used by Client if type=wpad
  connection_timeout: 10 # Client proxy connection timeout (seconds)
  request_timeout: 30 # Client proxy request/CONNECT timeout (seconds)
  max_retries: 3 # Client proxy connection retries

kerberos: # Hints for Client's Kerberos (uses user ccache)
  realm: "EXAMPLE.COM" # Optional hint for client
  enable_cache: true # Client always uses ccache in this model
  ticket_lifetime: 24 # Informational only
  cache_path: "" # Informational, client uses system default or krb5.conf

ebpf: # Configuration for Service's BPF programs
  target_ports: [80, 443] # Ports BPF sockops should check for redirection
  allow_dynamic_ports: true # Allow service to update target_ports map via IPC
  stats_interval: 15 # Service BPF stats logging interval (seconds)

# Service Logging configuration
log_level: "debug" # debug, info, warn, error
log_path: "/var/log/kernelgatekeeper.log" # Path for service logs, empty for stderr

# Service configuration
shutdown_timeout: 30 # Service graceful shutdown timeout (seconds)
socket_path: "/var/run/kernelgatekeeper.sock" # Service IPC socket path
