// FILE: pkg/ebpf/types.go
package ebpf

import "net"

// NotificationTuple holds processed data from a BPF notification event.
// Use this type in Go channels and application logic.
type NotificationTuple struct {
	PidTgid     uint64
	SrcIP       net.IP
	OrigDstIP   net.IP
	SrcPort     uint16
	OrigDstPort uint16
	Protocol    uint8
}

// BpfNotificationTupleT mirrors the C struct sent via the ring buffer.
// It should match the struct generated by bpf2go.
// We define it here for clarity in the reader, assuming bpf2go might
// generate it within its own files (e.g., bpf_sockopsNotificationTupleT).
// The reader will decode into this type.
type BpfNotificationTupleT struct {
	PidTgid     uint64
	SrcIp       uint32 // Note: Name matches C struct field (BigEndian)
	OrigDstIp   uint32 // Note: Name matches C struct field (BigEndian)
	SrcPort     uint16 // Note: Name matches C struct field (Network Byte Order)
	OrigDstPort uint16 // Note: Name matches C struct field (Network Byte Order)
	Protocol    uint8
	// Padding might be present depending on actual C struct and alignment
}
